package no.smalltypes.norwegian.bank;

public class InvalidKontonummerException extends RuntimeException {
	
	/**
	 * autogenerated
	 */
	private static final long serialVersionUID = 1L;

	public InvalidKontonummerException(String message) {
		super(message);
	}
	
	public InvalidKontonummerException(String message, Throwable cause) {
		super(message, cause);
	}	
	
}
